public class OOPComments {
}

/*

    What is OOP?
        - Object Oriented Programming
        - Programming design paradigm
        - Follows (in general) 4 basic pillars or tenants

    Pillars of OOP
        - Encapsulation : The practice of only giving access to others what is explicitly necessary
                            (protecting the internal state of the object)
            - Access Modifiers
            - Properties
        - Abstraction : The practice of hiding away complexity except where it is necessary for implementation
            - Abstract methods
            - Abstract classes
            - Interfaces
        - Inheritance : The practice of using functionality already written by another class or interface
            - Extend a class
            - Implement an interface
        - Polymorphism : The practice of allowing functions to adjust functionality based on context
                            (parameters or object the function is attached to)
            - Method overloading
            - Method overriding
            - Constructor chaining
            - Virtual keyword
*/

